/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as HealthRouteImport } from './routes/health'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeWishlistRouteImport } from './routes/$countryCode/wishlist'
import { Route as CountryCodeTrackRouteImport } from './routes/$countryCode/track'
import { Route as CountryCodeTermsRouteImport } from './routes/$countryCode/terms'
import { Route as CountryCodeSubscriptionsRouteImport } from './routes/$countryCode/subscriptions'
import { Route as CountryCodeStoresRouteImport } from './routes/$countryCode/stores'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeReturnsRouteImport } from './routes/$countryCode/returns'
import { Route as CountryCodePrivacyRouteImport } from './routes/$countryCode/privacy'
import { Route as CountryCodeLoyaltyRouteImport } from './routes/$countryCode/loyalty'
import { Route as CountryCodeLookbookRouteImport } from './routes/$countryCode/lookbook'
import { Route as CountryCodeHelpRouteImport } from './routes/$countryCode/help'
import { Route as CountryCodeGiftCardsRouteImport } from './routes/$countryCode/gift-cards'
import { Route as CountryCodeFaqRouteImport } from './routes/$countryCode/faq'
import { Route as CountryCodeContactRouteImport } from './routes/$countryCode/contact'
import { Route as CountryCodeCompareRouteImport } from './routes/$countryCode/compare'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeBlogRouteImport } from './routes/$countryCode/blog'
import { Route as CountryCodeAboutRouteImport } from './routes/$countryCode/about'
import { Route as CountryCodeVendorsIndexRouteImport } from './routes/$countryCode/vendors/index'
import { Route as CountryCodeServicesIndexRouteImport } from './routes/$countryCode/services/index'
import { Route as CountryCodeBlogIndexRouteImport } from './routes/$countryCode/blog/index'
import { Route as CountryCodeAccountIndexRouteImport } from './routes/$countryCode/account/index'
import { Route as CountryCodeVendorsHandleRouteImport } from './routes/$countryCode/vendors/$handle'
import { Route as CountryCodeServicesHandleRouteImport } from './routes/$countryCode/services/$handle'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeOrdersOrderIdRouteImport } from './routes/$countryCode/orders/$orderId'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeAccountWalletRouteImport } from './routes/$countryCode/account/wallet'
import { Route as CountryCodeAccountSettingsRouteImport } from './routes/$countryCode/account/settings'
import { Route as CountryCodeAccountRegisterRouteImport } from './routes/$countryCode/account/register'
import { Route as CountryCodeAccountLoyaltyRouteImport } from './routes/$countryCode/account/loyalty'
import { Route as CountryCodeAccountLoginRouteImport } from './routes/$countryCode/account/login'
import { Route as CountryCodeAccountIdentityRouteImport } from './routes/$countryCode/account/identity'
import { Route as CountryCodeAccountCreditsRouteImport } from './routes/$countryCode/account/credits'
import { Route as CountryCodeAccountBusinessRouteImport } from './routes/$countryCode/account/business'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeWishlistRoute = CountryCodeWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeTrackRoute = CountryCodeTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeTermsRoute = CountryCodeTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeSubscriptionsRoute =
  CountryCodeSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeStoresRoute = CountryCodeStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeReturnsRoute = CountryCodeReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodePrivacyRoute = CountryCodePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeLoyaltyRoute = CountryCodeLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeLookbookRoute = CountryCodeLookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeHelpRoute = CountryCodeHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeGiftCardsRoute = CountryCodeGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeFaqRoute = CountryCodeFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeContactRoute = CountryCodeContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCompareRoute = CountryCodeCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeBlogRoute = CountryCodeBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAboutRoute = CountryCodeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorsIndexRoute = CountryCodeVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeServicesIndexRoute =
  CountryCodeServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeBlogIndexRoute = CountryCodeBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeBlogRoute,
} as any)
const CountryCodeAccountIndexRoute = CountryCodeAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeVendorsHandleRoute =
  CountryCodeVendorsHandleRouteImport.update({
    id: '/vendors/$handle',
    path: '/vendors/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeServicesHandleRoute =
  CountryCodeServicesHandleRouteImport.update({
    id: '/services/$handle',
    path: '/services/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrdersOrderIdRoute =
  CountryCodeOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountWalletRoute =
  CountryCodeAccountWalletRouteImport.update({
    id: '/account/wallet',
    path: '/account/wallet',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountSettingsRoute =
  CountryCodeAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountRegisterRoute =
  CountryCodeAccountRegisterRouteImport.update({
    id: '/account/register',
    path: '/account/register',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountLoyaltyRoute =
  CountryCodeAccountLoyaltyRouteImport.update({
    id: '/account/loyalty',
    path: '/account/loyalty',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountLoginRoute = CountryCodeAccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountIdentityRoute =
  CountryCodeAccountIdentityRouteImport.update({
    id: '/account/identity',
    path: '/account/identity',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountCreditsRoute =
  CountryCodeAccountCreditsRouteImport.update({
    id: '/account/credits',
    path: '/account/credits',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountBusinessRoute =
  CountryCodeAccountBusinessRouteImport.update({
    id: '/account/business',
    path: '/account/business',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/about': typeof CountryCodeAboutRoute
  '/$countryCode/blog': typeof CountryCodeBlogRouteWithChildren
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/compare': typeof CountryCodeCompareRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/faq': typeof CountryCodeFaqRoute
  '/$countryCode/gift-cards': typeof CountryCodeGiftCardsRoute
  '/$countryCode/help': typeof CountryCodeHelpRoute
  '/$countryCode/lookbook': typeof CountryCodeLookbookRoute
  '/$countryCode/loyalty': typeof CountryCodeLoyaltyRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/returns': typeof CountryCodeReturnsRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode/subscriptions': typeof CountryCodeSubscriptionsRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/track': typeof CountryCodeTrackRoute
  '/$countryCode/wishlist': typeof CountryCodeWishlistRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/business': typeof CountryCodeAccountBusinessRoute
  '/$countryCode/account/credits': typeof CountryCodeAccountCreditsRoute
  '/$countryCode/account/identity': typeof CountryCodeAccountIdentityRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/loyalty': typeof CountryCodeAccountLoyaltyRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/account/settings': typeof CountryCodeAccountSettingsRoute
  '/$countryCode/account/wallet': typeof CountryCodeAccountWalletRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/orders/$orderId': typeof CountryCodeOrdersOrderIdRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/services/$handle': typeof CountryCodeServicesHandleRoute
  '/$countryCode/vendors/$handle': typeof CountryCodeVendorsHandleRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/blog/': typeof CountryCodeBlogIndexRoute
  '/$countryCode/services/': typeof CountryCodeServicesIndexRoute
  '/$countryCode/vendors/': typeof CountryCodeVendorsIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/about': typeof CountryCodeAboutRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/compare': typeof CountryCodeCompareRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/faq': typeof CountryCodeFaqRoute
  '/$countryCode/gift-cards': typeof CountryCodeGiftCardsRoute
  '/$countryCode/help': typeof CountryCodeHelpRoute
  '/$countryCode/lookbook': typeof CountryCodeLookbookRoute
  '/$countryCode/loyalty': typeof CountryCodeLoyaltyRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/returns': typeof CountryCodeReturnsRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode/subscriptions': typeof CountryCodeSubscriptionsRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/track': typeof CountryCodeTrackRoute
  '/$countryCode/wishlist': typeof CountryCodeWishlistRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/account/business': typeof CountryCodeAccountBusinessRoute
  '/$countryCode/account/credits': typeof CountryCodeAccountCreditsRoute
  '/$countryCode/account/identity': typeof CountryCodeAccountIdentityRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/loyalty': typeof CountryCodeAccountLoyaltyRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/account/settings': typeof CountryCodeAccountSettingsRoute
  '/$countryCode/account/wallet': typeof CountryCodeAccountWalletRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/orders/$orderId': typeof CountryCodeOrdersOrderIdRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/services/$handle': typeof CountryCodeServicesHandleRoute
  '/$countryCode/vendors/$handle': typeof CountryCodeVendorsHandleRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/blog': typeof CountryCodeBlogIndexRoute
  '/$countryCode/services': typeof CountryCodeServicesIndexRoute
  '/$countryCode/vendors': typeof CountryCodeVendorsIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/health': typeof HealthRoute
  '/store': typeof StoreRoute
  '/$countryCode/about': typeof CountryCodeAboutRoute
  '/$countryCode/blog': typeof CountryCodeBlogRouteWithChildren
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/compare': typeof CountryCodeCompareRoute
  '/$countryCode/contact': typeof CountryCodeContactRoute
  '/$countryCode/faq': typeof CountryCodeFaqRoute
  '/$countryCode/gift-cards': typeof CountryCodeGiftCardsRoute
  '/$countryCode/help': typeof CountryCodeHelpRoute
  '/$countryCode/lookbook': typeof CountryCodeLookbookRoute
  '/$countryCode/loyalty': typeof CountryCodeLoyaltyRoute
  '/$countryCode/privacy': typeof CountryCodePrivacyRoute
  '/$countryCode/returns': typeof CountryCodeReturnsRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/stores': typeof CountryCodeStoresRoute
  '/$countryCode/subscriptions': typeof CountryCodeSubscriptionsRoute
  '/$countryCode/terms': typeof CountryCodeTermsRoute
  '/$countryCode/track': typeof CountryCodeTrackRoute
  '/$countryCode/wishlist': typeof CountryCodeWishlistRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/business': typeof CountryCodeAccountBusinessRoute
  '/$countryCode/account/credits': typeof CountryCodeAccountCreditsRoute
  '/$countryCode/account/identity': typeof CountryCodeAccountIdentityRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/loyalty': typeof CountryCodeAccountLoyaltyRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/account/settings': typeof CountryCodeAccountSettingsRoute
  '/$countryCode/account/wallet': typeof CountryCodeAccountWalletRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/orders/$orderId': typeof CountryCodeOrdersOrderIdRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/services/$handle': typeof CountryCodeServicesHandleRoute
  '/$countryCode/vendors/$handle': typeof CountryCodeVendorsHandleRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/blog/': typeof CountryCodeBlogIndexRoute
  '/$countryCode/services/': typeof CountryCodeServicesIndexRoute
  '/$countryCode/vendors/': typeof CountryCodeVendorsIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/about'
    | '/$countryCode/blog'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/compare'
    | '/$countryCode/contact'
    | '/$countryCode/faq'
    | '/$countryCode/gift-cards'
    | '/$countryCode/help'
    | '/$countryCode/lookbook'
    | '/$countryCode/loyalty'
    | '/$countryCode/privacy'
    | '/$countryCode/returns'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode/subscriptions'
    | '/$countryCode/terms'
    | '/$countryCode/track'
    | '/$countryCode/wishlist'
    | '/$countryCode/'
    | '/$countryCode/account/business'
    | '/$countryCode/account/credits'
    | '/$countryCode/account/identity'
    | '/$countryCode/account/login'
    | '/$countryCode/account/loyalty'
    | '/$countryCode/account/register'
    | '/$countryCode/account/settings'
    | '/$countryCode/account/wallet'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/orders/$orderId'
    | '/$countryCode/products/$handle'
    | '/$countryCode/services/$handle'
    | '/$countryCode/vendors/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/blog/'
    | '/$countryCode/services/'
    | '/$countryCode/vendors/'
    | '/$countryCode/order/$orderId/confirmed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/about'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/compare'
    | '/$countryCode/contact'
    | '/$countryCode/faq'
    | '/$countryCode/gift-cards'
    | '/$countryCode/help'
    | '/$countryCode/lookbook'
    | '/$countryCode/loyalty'
    | '/$countryCode/privacy'
    | '/$countryCode/returns'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode/subscriptions'
    | '/$countryCode/terms'
    | '/$countryCode/track'
    | '/$countryCode/wishlist'
    | '/$countryCode'
    | '/$countryCode/account/business'
    | '/$countryCode/account/credits'
    | '/$countryCode/account/identity'
    | '/$countryCode/account/login'
    | '/$countryCode/account/loyalty'
    | '/$countryCode/account/register'
    | '/$countryCode/account/settings'
    | '/$countryCode/account/wallet'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/orders/$orderId'
    | '/$countryCode/products/$handle'
    | '/$countryCode/services/$handle'
    | '/$countryCode/vendors/$handle'
    | '/$countryCode/account'
    | '/$countryCode/blog'
    | '/$countryCode/services'
    | '/$countryCode/vendors'
    | '/$countryCode/order/$orderId/confirmed'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/cart'
    | '/checkout'
    | '/health'
    | '/store'
    | '/$countryCode/about'
    | '/$countryCode/blog'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/compare'
    | '/$countryCode/contact'
    | '/$countryCode/faq'
    | '/$countryCode/gift-cards'
    | '/$countryCode/help'
    | '/$countryCode/lookbook'
    | '/$countryCode/loyalty'
    | '/$countryCode/privacy'
    | '/$countryCode/returns'
    | '/$countryCode/store'
    | '/$countryCode/stores'
    | '/$countryCode/subscriptions'
    | '/$countryCode/terms'
    | '/$countryCode/track'
    | '/$countryCode/wishlist'
    | '/$countryCode/'
    | '/$countryCode/account/business'
    | '/$countryCode/account/credits'
    | '/$countryCode/account/identity'
    | '/$countryCode/account/login'
    | '/$countryCode/account/loyalty'
    | '/$countryCode/account/register'
    | '/$countryCode/account/settings'
    | '/$countryCode/account/wallet'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/orders/$orderId'
    | '/$countryCode/products/$handle'
    | '/$countryCode/services/$handle'
    | '/$countryCode/vendors/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/blog/'
    | '/$countryCode/services/'
    | '/$countryCode/vendors/'
    | '/$countryCode/order/$orderId/confirmed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HealthRoute: typeof HealthRoute
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/wishlist': {
      id: '/$countryCode/wishlist'
      path: '/wishlist'
      fullPath: '/$countryCode/wishlist'
      preLoaderRoute: typeof CountryCodeWishlistRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/track': {
      id: '/$countryCode/track'
      path: '/track'
      fullPath: '/$countryCode/track'
      preLoaderRoute: typeof CountryCodeTrackRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/terms': {
      id: '/$countryCode/terms'
      path: '/terms'
      fullPath: '/$countryCode/terms'
      preLoaderRoute: typeof CountryCodeTermsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/subscriptions': {
      id: '/$countryCode/subscriptions'
      path: '/subscriptions'
      fullPath: '/$countryCode/subscriptions'
      preLoaderRoute: typeof CountryCodeSubscriptionsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/stores': {
      id: '/$countryCode/stores'
      path: '/stores'
      fullPath: '/$countryCode/stores'
      preLoaderRoute: typeof CountryCodeStoresRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/returns': {
      id: '/$countryCode/returns'
      path: '/returns'
      fullPath: '/$countryCode/returns'
      preLoaderRoute: typeof CountryCodeReturnsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/privacy': {
      id: '/$countryCode/privacy'
      path: '/privacy'
      fullPath: '/$countryCode/privacy'
      preLoaderRoute: typeof CountryCodePrivacyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/loyalty': {
      id: '/$countryCode/loyalty'
      path: '/loyalty'
      fullPath: '/$countryCode/loyalty'
      preLoaderRoute: typeof CountryCodeLoyaltyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/lookbook': {
      id: '/$countryCode/lookbook'
      path: '/lookbook'
      fullPath: '/$countryCode/lookbook'
      preLoaderRoute: typeof CountryCodeLookbookRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/help': {
      id: '/$countryCode/help'
      path: '/help'
      fullPath: '/$countryCode/help'
      preLoaderRoute: typeof CountryCodeHelpRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/gift-cards': {
      id: '/$countryCode/gift-cards'
      path: '/gift-cards'
      fullPath: '/$countryCode/gift-cards'
      preLoaderRoute: typeof CountryCodeGiftCardsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/faq': {
      id: '/$countryCode/faq'
      path: '/faq'
      fullPath: '/$countryCode/faq'
      preLoaderRoute: typeof CountryCodeFaqRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/contact': {
      id: '/$countryCode/contact'
      path: '/contact'
      fullPath: '/$countryCode/contact'
      preLoaderRoute: typeof CountryCodeContactRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/compare': {
      id: '/$countryCode/compare'
      path: '/compare'
      fullPath: '/$countryCode/compare'
      preLoaderRoute: typeof CountryCodeCompareRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/blog': {
      id: '/$countryCode/blog'
      path: '/blog'
      fullPath: '/$countryCode/blog'
      preLoaderRoute: typeof CountryCodeBlogRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/about': {
      id: '/$countryCode/about'
      path: '/about'
      fullPath: '/$countryCode/about'
      preLoaderRoute: typeof CountryCodeAboutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendors/': {
      id: '/$countryCode/vendors/'
      path: '/vendors'
      fullPath: '/$countryCode/vendors/'
      preLoaderRoute: typeof CountryCodeVendorsIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/services/': {
      id: '/$countryCode/services/'
      path: '/services'
      fullPath: '/$countryCode/services/'
      preLoaderRoute: typeof CountryCodeServicesIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/blog/': {
      id: '/$countryCode/blog/'
      path: '/'
      fullPath: '/$countryCode/blog/'
      preLoaderRoute: typeof CountryCodeBlogIndexRouteImport
      parentRoute: typeof CountryCodeBlogRoute
    }
    '/$countryCode/account/': {
      id: '/$countryCode/account/'
      path: '/account'
      fullPath: '/$countryCode/account/'
      preLoaderRoute: typeof CountryCodeAccountIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/vendors/$handle': {
      id: '/$countryCode/vendors/$handle'
      path: '/vendors/$handle'
      fullPath: '/$countryCode/vendors/$handle'
      preLoaderRoute: typeof CountryCodeVendorsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/services/$handle': {
      id: '/$countryCode/services/$handle'
      path: '/services/$handle'
      fullPath: '/$countryCode/services/$handle'
      preLoaderRoute: typeof CountryCodeServicesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/orders/$orderId': {
      id: '/$countryCode/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/$countryCode/orders/$orderId'
      preLoaderRoute: typeof CountryCodeOrdersOrderIdRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/wallet': {
      id: '/$countryCode/account/wallet'
      path: '/account/wallet'
      fullPath: '/$countryCode/account/wallet'
      preLoaderRoute: typeof CountryCodeAccountWalletRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/settings': {
      id: '/$countryCode/account/settings'
      path: '/account/settings'
      fullPath: '/$countryCode/account/settings'
      preLoaderRoute: typeof CountryCodeAccountSettingsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/register': {
      id: '/$countryCode/account/register'
      path: '/account/register'
      fullPath: '/$countryCode/account/register'
      preLoaderRoute: typeof CountryCodeAccountRegisterRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/loyalty': {
      id: '/$countryCode/account/loyalty'
      path: '/account/loyalty'
      fullPath: '/$countryCode/account/loyalty'
      preLoaderRoute: typeof CountryCodeAccountLoyaltyRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/login': {
      id: '/$countryCode/account/login'
      path: '/account/login'
      fullPath: '/$countryCode/account/login'
      preLoaderRoute: typeof CountryCodeAccountLoginRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/identity': {
      id: '/$countryCode/account/identity'
      path: '/account/identity'
      fullPath: '/$countryCode/account/identity'
      preLoaderRoute: typeof CountryCodeAccountIdentityRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/credits': {
      id: '/$countryCode/account/credits'
      path: '/account/credits'
      fullPath: '/$countryCode/account/credits'
      preLoaderRoute: typeof CountryCodeAccountCreditsRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/business': {
      id: '/$countryCode/account/business'
      path: '/account/business'
      fullPath: '/$countryCode/account/business'
      preLoaderRoute: typeof CountryCodeAccountBusinessRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
  }
}

interface CountryCodeBlogRouteChildren {
  CountryCodeBlogIndexRoute: typeof CountryCodeBlogIndexRoute
}

const CountryCodeBlogRouteChildren: CountryCodeBlogRouteChildren = {
  CountryCodeBlogIndexRoute: CountryCodeBlogIndexRoute,
}

const CountryCodeBlogRouteWithChildren = CountryCodeBlogRoute._addFileChildren(
  CountryCodeBlogRouteChildren,
)

interface CountryCodeRouteChildren {
  CountryCodeAboutRoute: typeof CountryCodeAboutRoute
  CountryCodeBlogRoute: typeof CountryCodeBlogRouteWithChildren
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeCompareRoute: typeof CountryCodeCompareRoute
  CountryCodeContactRoute: typeof CountryCodeContactRoute
  CountryCodeFaqRoute: typeof CountryCodeFaqRoute
  CountryCodeGiftCardsRoute: typeof CountryCodeGiftCardsRoute
  CountryCodeHelpRoute: typeof CountryCodeHelpRoute
  CountryCodeLookbookRoute: typeof CountryCodeLookbookRoute
  CountryCodeLoyaltyRoute: typeof CountryCodeLoyaltyRoute
  CountryCodePrivacyRoute: typeof CountryCodePrivacyRoute
  CountryCodeReturnsRoute: typeof CountryCodeReturnsRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeStoresRoute: typeof CountryCodeStoresRoute
  CountryCodeSubscriptionsRoute: typeof CountryCodeSubscriptionsRoute
  CountryCodeTermsRoute: typeof CountryCodeTermsRoute
  CountryCodeTrackRoute: typeof CountryCodeTrackRoute
  CountryCodeWishlistRoute: typeof CountryCodeWishlistRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeAccountBusinessRoute: typeof CountryCodeAccountBusinessRoute
  CountryCodeAccountCreditsRoute: typeof CountryCodeAccountCreditsRoute
  CountryCodeAccountIdentityRoute: typeof CountryCodeAccountIdentityRoute
  CountryCodeAccountLoginRoute: typeof CountryCodeAccountLoginRoute
  CountryCodeAccountLoyaltyRoute: typeof CountryCodeAccountLoyaltyRoute
  CountryCodeAccountRegisterRoute: typeof CountryCodeAccountRegisterRoute
  CountryCodeAccountSettingsRoute: typeof CountryCodeAccountSettingsRoute
  CountryCodeAccountWalletRoute: typeof CountryCodeAccountWalletRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeOrdersOrderIdRoute: typeof CountryCodeOrdersOrderIdRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeServicesHandleRoute: typeof CountryCodeServicesHandleRoute
  CountryCodeVendorsHandleRoute: typeof CountryCodeVendorsHandleRoute
  CountryCodeAccountIndexRoute: typeof CountryCodeAccountIndexRoute
  CountryCodeServicesIndexRoute: typeof CountryCodeServicesIndexRoute
  CountryCodeVendorsIndexRoute: typeof CountryCodeVendorsIndexRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeAboutRoute: CountryCodeAboutRoute,
  CountryCodeBlogRoute: CountryCodeBlogRouteWithChildren,
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeCompareRoute: CountryCodeCompareRoute,
  CountryCodeContactRoute: CountryCodeContactRoute,
  CountryCodeFaqRoute: CountryCodeFaqRoute,
  CountryCodeGiftCardsRoute: CountryCodeGiftCardsRoute,
  CountryCodeHelpRoute: CountryCodeHelpRoute,
  CountryCodeLookbookRoute: CountryCodeLookbookRoute,
  CountryCodeLoyaltyRoute: CountryCodeLoyaltyRoute,
  CountryCodePrivacyRoute: CountryCodePrivacyRoute,
  CountryCodeReturnsRoute: CountryCodeReturnsRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeStoresRoute: CountryCodeStoresRoute,
  CountryCodeSubscriptionsRoute: CountryCodeSubscriptionsRoute,
  CountryCodeTermsRoute: CountryCodeTermsRoute,
  CountryCodeTrackRoute: CountryCodeTrackRoute,
  CountryCodeWishlistRoute: CountryCodeWishlistRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeAccountBusinessRoute: CountryCodeAccountBusinessRoute,
  CountryCodeAccountCreditsRoute: CountryCodeAccountCreditsRoute,
  CountryCodeAccountIdentityRoute: CountryCodeAccountIdentityRoute,
  CountryCodeAccountLoginRoute: CountryCodeAccountLoginRoute,
  CountryCodeAccountLoyaltyRoute: CountryCodeAccountLoyaltyRoute,
  CountryCodeAccountRegisterRoute: CountryCodeAccountRegisterRoute,
  CountryCodeAccountSettingsRoute: CountryCodeAccountSettingsRoute,
  CountryCodeAccountWalletRoute: CountryCodeAccountWalletRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeOrdersOrderIdRoute: CountryCodeOrdersOrderIdRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeServicesHandleRoute: CountryCodeServicesHandleRoute,
  CountryCodeVendorsHandleRoute: CountryCodeVendorsHandleRoute,
  CountryCodeAccountIndexRoute: CountryCodeAccountIndexRoute,
  CountryCodeServicesIndexRoute: CountryCodeServicesIndexRoute,
  CountryCodeVendorsIndexRoute: CountryCodeVendorsIndexRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HealthRoute: HealthRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
